language: go
sudo: false
go:
  # Support two major versions back; see policy at
  # https://golang.org/doc/devel/release.html#policy
  - "1.11"
  - "1.12"
  - "1.13"
  - master
before_install:
  - go get -u golang.org/x/lint/golint
script:
  - go get -t ./...
  - go build ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go vet ./...
  - golint --set_exit_status ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  except:
    - /.*-wip$/
