language: go
sudo: false
go:
  - 1.8
  - "1.10"
  - "1.11"
  - master
before_install:
  - go get github.com/mattn/goveralls
  - go get -u golang.org/x/lint/golint
script:
  - go get -t ./...
  - go build ./...
  - go test ./...
  - go vet ./...
  - golint --set_exit_status ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
branches:
  except:
    - /.*-wip$/
