language: go
sudo: false
go:
  - 1.8
  - 1.10
  - master
before_install:
  - go get github.com/mattn/goveralls
script:
  - go get -t ./...
  - go build ./...
  - go test ./...
  - go vet ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
branches:
  except:
    - /.*-wip$/
