runtime: go112

handlers:
- url: /update
  script: auto
- url: /
  static_files: appengine/view/index.html
  upload: appengine/view/index.html

env_variables:
  CLOUD_STORAGE_BUCKET: repy-176217.appspot.com
