runtime: go111

handlers:
- url: /update
  script: auto
  login: admin
- url: /view
  static_files: view/index.html
  upload: view/index.html
- url: /
  static_files: view/index.html
  upload: view/index.html
